//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cooperate_mvc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Comment
    {
        public Comment()
        {
            this.Comment1 = new HashSet<Comment>();
        }
    
        public long Comment_id { get; set; }
        public string Comment_text { get; set; }
        public int User_author { get; set; }
        public long Task_id { get; set; }
        public System.DateTime Comment_datetime { get; set; }
        public Nullable<long> Comment_inResponseTo { get; set; }
    
        public virtual ICollection<Comment> Comment1 { get; set; }
        public virtual Comment Comment2 { get; set; }
        public virtual Task Task { get; set; }
        public virtual User User { get; set; }
    }
}
