//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cooperate_mvc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Group
    {
        public Group()
        {
            this.Participations = new HashSet<Participation>();
            this.Posts = new HashSet<Post>();
            this.Tasks = new HashSet<Task>();
        }
    
        public long Group_id { get; set; }
        public string Group_name { get; set; }
        public string Group_description { get; set; }
        public System.DateTime Group_creationDate { get; set; }
    
        public virtual ICollection<Participation> Participations { get; set; }
        public virtual ICollection<Post> Posts { get; set; }
        public virtual ICollection<Task> Tasks { get; set; }
    }
}
