//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cooperate_mvc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Message
    {
        public long Message_id { get; set; }
        public string Message_text { get; set; }
        public System.DateTime Message_datetimt { get; set; }
        public int User_from { get; set; }
        public int User_to { get; set; }
    
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
    }
}
