//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cooperate_mvc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Post
    {
        public Post()
        {
            this.Post1 = new HashSet<Post>();
        }
    
        public long Post_id { get; set; }
        public string Post_text { get; set; }
        public int User_author { get; set; }
        public System.DateTime Post_datetime { get; set; }
        public Nullable<long> Post_inResponseTo { get; set; }
        public long Group_id { get; set; }
    
        public virtual Group Group { get; set; }
        public virtual ICollection<Post> Post1 { get; set; }
        public virtual Post Post2 { get; set; }
        public virtual User User { get; set; }
    }
}
