//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cooperate_mvc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TaskStatu
    {
        public TaskStatu()
        {
            this.Tasks = new HashSet<Task>();
        }
    
        public byte TaskStatus_id { get; set; }
        public string TaskStatus_name { get; set; }
    
        public virtual ICollection<Task> Tasks { get; set; }
    }
}
